export const PREPAR_FOR_THE_SIMULATION = 'PREPAR_FOR_THE_SIMULATION';
export const ERROR_DISPLAY = 'ERROR_DISPLAY';
export const RESTART = 'RESTART';
export const START_SIMULATION = 'START_SIMULATION';
